apiVersion: v1
kind: Service

metadata:
  name: reliable-api
  namespace: sre-platform
  labels:
    app: reliable-api

spec:
  selector:
    app: reliable-api

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000

  type: ClusterIP